# Generated by Django 5.0 on 2025-01-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_yangiliklar_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olimpiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fan', models.CharField(max_length=200)),
                ('Oqituvchi', models.CharField(max_length=200)),
                ('Oquvchi', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=200)),
                ('Sinf', models.CharField(max_length=20)),
                ('Orin', models.CharField(max_length=20)),
                ('Ball', models.CharField(max_length=20)),
            ],
        ),
    ]
