# Generated by Django 5.0 on 2025-01-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_olimpiada'),
    ]

    operations = [
        migrations.AddField(
            model_name='olimpiada',
            name='Yil',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='app', max_length=20),
            preserve_default=False,
        ),
    ]
