# Generated by Django 5.0 on 2025-01-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_olimpiada_yil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olimpiada',
            name='Oquvchi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='olimpiada',
            name='Sinf',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=20),
        ),
    ]
